### ISSUE TITLE
Please help with this error:  'weights/detector_weights/detector.pt' even though I added it as mentioned in readme file

### ISSUE THREAD

**Issue by ivedantmistry** [ValerioSpagnoli/vehicles-and-plate-detector#3]
```
PS C:\Users\iveda\Desktop\minor-github\EyeRoad\src> py test.py
Traceback (most recent call last):
  File "C:\Users\iveda\Desktop\minor-github\EyeRoad\src\test.py", line 5, in <module>
    detector = inference.load_model_for_inference(weights_file='weights/detector_weights/detector.pt', device='cpu')
  File "C:\Users\iveda\Desktop\minor-github\EyeRoad\src\modules\inference.py", line 10, in load_model_for_inference
    model.load_state_dict(torch.load(weights_file, map_location=torch.device(device)))
  File "c:\Users\iveda\Desktop\minor-github\.venv\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "c:\Users\iveda\Desktop\minor-github\.venv\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "c:\Users\iveda\Desktop\minor-github\.venv\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'weights/detector_weights/detector.pt'
PS C:\Users\iveda\Desktop\minor-github\EyeRoad\src> 
```

**Comment by ivedantmistry** [comment]
if i use this command 'python src/test.py' here is another error:

![image](https://github.com/ValerioSpagnoli/EyeRoad/assets/106006564/124f5e6c-e96c-47d2-a74e-e0f1b69af85c)

and if i remove the `frames_to_skip` argument from `real_time_object_detector.real_time_object_detector` from test.py, it generates result with first frame of my custom video in output_video directory
resultant image is here:
 
![0000000000](https://github.com/ValerioSpagnoli/EyeRoad/assets/106006564/2f9cf433-1a18-42c5-b2c2-f9942002130e)

**Comment by ivedantmistry** [comment]
my file structure:

![image](https://github.com/ValerioSpagnoli/EyeRoad/assets/106006564/173ba2df-273e-4ff9-8a74-c459cb99c885)

**Comment by ivedantmistry** [comment]
BTW using python 3.9.0 in virtual environment

**Comment by ValerioSpagnoli** [comment]
https://github.com/ValerioSpagnoli/EyeRoad/issues/3#issue-2279026910: This error comes out because you are running the `test.py` module inside `src`. Please run it from the root directory of this repository with the command `python3 src/test.py` (check `Usage` section of README.md).

https://github.com/ValerioSpagnoli/EyeRoad/issues/3#issuecomment-2094224488: This is due to my error. I just pushed the fix, please check if it works and let me know.

For any other problem, just ask ;)

**Comment by ivedantmistry** [comment]
hello @ValerioSpagnoli 
okay new push worked, but I had a question can't it generate a video rather than images of every frame (after detecting) or will it create a video after the execution of the test.py?

![image](https://github.com/ValerioSpagnoli/EyeRoad/assets/106006564/8109027d-58e2-4a93-a229-9a7be8299343)

**Comment by ValerioSpagnoli** [comment]
https://github.com/ValerioSpagnoli/EyeRoad/issues/3#issuecomment-2094368642: there is a python script in `src/utils` called `frames2video.py` that should be used exactly for this case. You can run it as you want, but to facilitate the usage I just pushed a fix both in `frames2video.py` (adding the main) both in `test.py` adding the module after the object detector (in this way is automatically executed after the generation of the frames).

**Comment by ivedantmistry** [comment]
okay works!
but when i edit `end_frame=-1` to convert wholevideo it throws error:

(.venv) PS C:\Users\iveda\Desktop\minor-github\eyeroad> python src/test.py
Folder 'output_video/' created successfully.
Traceback (most recent call last):
  File "C:\Users\iveda\Desktop\minor-github\eyeroad\src\test.py", line 7, in <module>
    real_time_object_detector.real_time_object_detector(model=detector,
  File "C:\Users\iveda\Desktop\minor-github\eyeroad\src\modules\real_time_object_detector.py", line 152, in real_time_object_detector
    new_frame, new_tracked_vehicles, counter = plot_one_image(model=model, image=frame, sr_weights_path=sr_weights_path, string_plate_detector=spd,
  File "C:\Users\iveda\Desktop\minor-github\eyeroad\src\modules\real_time_object_detector.py", line 89, in plot_one_image 
    sr = cv2.dnn_superres.DnnSuperResImpl_create()
AttributeError: module 'cv2' has no attribute 'dnn_superres'
(.venv) PS C:\Users\iveda\Desktop\minor-github\eyeroad>

**Comment by ValerioSpagnoli** [comment]
https://github.com/ValerioSpagnoli/EyeRoad/issues/3#issuecomment-2094555960: try to follow this https://stackoverflow.com/questions/64763274/module-cv2-cv2-has-no-attribute-dnn-superres.

**Comment by ivedantmistry** [comment]
thanks man it worked, closing this issue!
